Change the initialization for the Riak backend so it is consistent with how the other backends are being initialized.
Otherwise we get:

TypeError: __init__() got multiple values for keyword argument 'XXXXX'

When nydus tries to initialize the backend.